name: bytebandits
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_notifications: ^0.7.5-dev.3
  awesome_notifications_fcm: ^0.7.5-dev.3
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_cashfree_pg_sdk: ^2.0.12+15
  flutter_gen: ^5.3.1
  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.8.4
  fpdart: ^1.0.0-beta.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.3.2

flutter_gen:
  output: lib/app/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    # - assets/backgrounds/
    # - assets/animations/
